include: ./very_good_analysis.yaml

analyzer:
  language:
    # https://github.com/dart-lang/language/blob/master/resources/type-system/strict-casts.md
    strict-casts: true

    # https://github.com/dart-lang/language/blob/master/resources/type-system/strict-raw-types.md
    strict-raw-types: true

    # https://github.com/dart-lang/language/blob/master/resources/type-system/strict-inference.md
    strict-inference: true

  exclude:
    - "packages/**"
    - "example/**"
