name: flutter_bloc_hooks_example
version: 0.0.1
publish_to: none

environment:
  flutter: ">=2.10.4"
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter_bloc_hooks: 0.0.2+1
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.3
  flutter:
    sdk: flutter

dev_dependencies:
  dependency_validator: ^3.2.0

flutter:
  uses-material-design: true
