include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - flutter_hooks_lint_plugin

  language:
    # https://github.com/dart-lang/language/blob/master/resources/type-system/strict-raw-types.md
    strict-raw-types: true

    # https://github.com/dart-lang/language/blob/master/resources/type-system/strict-inference.md
    strict-inference: true

  # https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
